#!/bin/bash

# Check for extra blank lines at the end of files

# Stash so that unstaged changes are not checked
git stash -q --keep-index

# Set default exit status
exitStatus=0

while read -r filename; do
  # Check if the file is tracked by git
  if ! git ls-files --error-unmatch "$filename" &>/dev/null; then
    # Don't check untracked files
    continue
  fi

  if tail -1 "$filename" | grep --binary-files=without-match --regexp="^$"; then
    echo "ERROR: Blank line found at end of $filename"
    # Make the hook fail
    exitStatus=1
  fi
done <<<"$(find . -path './.git' -prune -or -type f)"

git stash pop -q

exit $exitStatus
