#!/bin/bash

# Check for files with UTF-8 BOM encoding

# Stash so that unstaged changes are not checked
git stash -q --keep-index

# Set default exit status
exitStatus=0

while read -r filename; do
  # Check if the file is tracked by git
  if ! git ls-files --error-unmatch "$filename" &>/dev/null; then
    # Don't check untracked files
    continue
  fi

  if grep --files-with-matches --binary-files=without-match $'\xEF\xBB\xBF' "$filename"; then
    echo "ERROR: $filename uses UTF-8 BOM encoding"
    # Make the hook fail
    exitStatus=1
  fi
done <<<"$(find . -path './.git' -prune -or -type f)"

git stash pop -q

exit $exitStatus
