#!/bin/bash

# Check for true tabs

# Stash so that unstaged changes are not checked
git stash -q --keep-index

# Set default exit status
exitStatus=0

while read -r filename; do
  # Check if the file is tracked by git
  if ! git ls-files --error-unmatch "$filename" &>/dev/null; then
    # don't check untracked files
    continue
  fi

  if grep --with-filename --line-number --binary-files=without-match --regexp=$'\t' "$filename"; then
    echo "ERROR: True tab found in $filename"
    # Make the hook fail
    exitStatus=1
  fi
done <<<"$(find . -path './.git' -prune -or -type f)"

git stash pop -q

exit $exitStatus
